### ISSUE TITLE
"can't perform spi transfer: invalid argument " with 4.1.7 kernel

### ISSUE THREAD

**Issue by davidlegoff** [lehenbauer/tclspi#1]
Hi,

I was just trying your package on a 4.1.7 raspberry PI and got the following error message when trying to use the test.tcl script:
"can't perform spi transfer: invalid argument"

To solve the issue a clear of the spi struct is required before using it.

I just added this line after the spi struct declaration:
memset (&spi, 0, sizeof(spi));

Hope this helps,

David

**Comment by StephaneThiebaut** [comment]
Hello,
I've got the same error, with kernel 4.4.13+
Stephane

**Comment by lehenbauer** [comment]
Hi, yeah, something changed in Raspbian where it gets that error sometimes.  (It used to never do that.)  I have dug into the kernel’s SPI driver and looked at all the cases where it can return EINVAL and haven’t been able to figure out what it thinks is wrong.

On Sep 10, 2016, at 2:53 PM, StephaneThiebaut <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,
I've got the same error, with kernel 4.4.13+
Stephane

**Comment by StephaneThiebaut** [comment]
Thank you for this answer. I cleared the spi struct as suggested by @davidlegoff and it works for me too. Thanks for this driver, it saves me lot of time.

**Comment by lehenbauer** [comment]
OMG he provided the answer last year!  I think in the mail I only saw an extract… that or I didn’t read far enough!  OK I will fix this.  Thank you very much.

**Comment by lehenbauer** [comment]
Fixed by commit 6c61629da200e681d99a8b55a33c979bcdf9dbf3 and present in release 1.0.1.
